import type { ProblemDef } from '../types.js';
import { editorial } from '../helpers.js';

const BIG_TECH = ['Google', 'Amazon', 'Meta', 'Microsoft', 'Apple'];

export const BATCH_02: ProblemDef[] = [
  {
    slug: 'best-time-to-buy-and-sell-stock',
    title: 'Best Time to Buy and Sell Stock',
    difficulty: 'EASY',
    topic: 'ARRAYS',
    tags: ['array', 'dynamic-programming'],
    companies: BIG_TECH,
    description: 'Maximize profit from one buy and one sell on different days.',
    fullDescription: `You are given an array \`prices\` where \`prices[i]\` is the price on day \`i\`. You want to maximize profit by choosing **one day to buy** and **one day in the future to sell**. Return the maximum profit. If you cannot profit, return \`0\`.`,
    constraints: `1 <= prices.length <= 10^5\n0 <= prices[i] <= 10^4`,
    examples: [
      { input: 'prices = [7,1,5,3,6,4]', output: '5', explanation: 'Buy day 1 (1), sell day 4 (6), profit 5.' },
      { input: 'prices = [7,6,4,3,1]', output: '0', explanation: 'No profitable transaction.' },
    ],
    edgeCases: ['Strictly decreasing prices', 'Single day'],
    hints: ['Track minimum price seen so far.', 'At each day, profit if sold today is price - min.', 'Keep global maximum profit.'],
    editorial: editorial('Try all buy/sell pairs.', 'Track min price while scanning.', 'Single pass min + max profit.', 'O(n)', 'O(1)'),
    relatedSlugs: ['best-time-to-buy-and-sell-stock-ii', 'maximum-subarray', 'contains-duplicate'],
    orderIndex: 10,
    py: `def max_profit(prices):\n    mn, best = float('inf'), 0\n    for p in prices:\n        mn = min(mn, p)\n        best = max(best, p - mn)\n    return best\n\nresult = max_profit(data["prices"])`,
    js: `function maxProfit(prices) {\n  let mn = Infinity, best = 0;\n  for (const p of prices) { mn = Math.min(mn, p); best = Math.max(best, p - mn); }\n  return best;\n}\nconst result = maxProfit(data.prices);`,
    testCases: [
      { input: '{"prices":[7,1,5,3,6,4]}', expectedOutput: '5' },
      { input: '{"prices":[7,6,4,3,1]}', expectedOutput: '0', isHidden: true },
    ],
  },
  {
    slug: 'longest-substring-without-repeating-characters',
    title: 'Longest Substring Without Repeating Characters',
    difficulty: 'MEDIUM',
    topic: 'STRINGS',
    tags: ['string', 'sliding-window', 'hash-table'],
    companies: BIG_TECH,
    description: 'Length of the longest substring without repeating characters.',
    fullDescription: `Given a string \`s\`, find the length of the **longest substring** without repeating characters.`,
    constraints: `0 <= s.length <= 5 * 10^4\ns consists of English letters, digits, symbols.`,
    examples: [
      { input: 's = "abcabcbb"', output: '3', explanation: '"abc" has length 3.' },
      { input: 's = "bbbbb"', output: '1', explanation: '"b" only.' },
    ],
    edgeCases: ['Empty string', 'All unique characters'],
    hints: ['Expand window while characters are unique.', 'Shrink from left when duplicate found.', 'Store last index of each character.'],
    editorial: editorial('Check all substrings — O(n^3).', 'Sliding window with set.', 'Window with char -> last index map.', 'O(n)', 'O(min(n, alphabet))'),
    relatedSlugs: ['minimum-window-substring', 'longest-repeating-character-replacement', 'valid-parentheses'],
    orderIndex: 11,
    py: `def length_of_longest(s):\n    seen = {}\n    start = best = 0\n    for i, c in enumerate(s):\n        if c in seen and seen[c] >= start:\n            start = seen[c] + 1\n        seen[c] = i\n        best = max(best, i - start + 1)\n    return best\n\nresult = length_of_longest(data["s"])`,
    js: `function lengthOfLongest(s) {\n  const seen = new Map();\n  let start = 0, best = 0;\n  for (let i = 0; i < s.length; i++) {\n    if (seen.has(s[i]) && seen.get(s[i]) >= start) start = seen.get(s[i]) + 1;\n    seen.set(s[i], i);\n    best = Math.max(best, i - start + 1);\n  }\n  return best;\n}\nconst result = lengthOfLongest(data.s);`,
    testCases: [
      { input: '{"s":"abcabcbb"}', expectedOutput: '3' },
      { input: '{"s":"pwwkew"}', expectedOutput: '3', isHidden: true },
    ],
  },
  {
    slug: 'valid-anagram',
    title: 'Valid Anagram',
    difficulty: 'EASY',
    topic: 'STRINGS',
    tags: ['string', 'hash-table', 'sorting'],
    companies: ['Amazon', 'Facebook', 'Bloomberg'],
    description: 'Return true if t is an anagram of s.',
    fullDescription: `Given two strings \`s\` and \`t\`, return \`true\` if \`t\` is an anagram of \`s\`, and \`false\` otherwise.`,
    constraints: `1 <= s.length, t.length <= 5 * 10^4\ns and t consist of lowercase English letters.`,
    examples: [
      { input: 's = "anagram", t = "nagaram"', output: 'true' },
      { input: 's = "rat", t = "car"', output: 'false' },
    ],
    edgeCases: ['Different lengths', 'Identical strings'],
    hints: ['Sort both strings and compare.', 'Count character frequencies in s and subtract using t.', 'If all counts are zero, it is an anagram.'],
    editorial: editorial('Sort and compare.', 'Two frequency arrays.', 'Single frequency array with +/-.', 'O(n)', 'O(1) alphabet size'),
    relatedSlugs: ['group-anagrams', 'find-all-anagrams-in-a-string', 'contains-duplicate'],
    orderIndex: 12,
    py: `from collections import Counter\nresult = Counter(data["s"]) == Counter(data["t"])`,
    js: `function isAnagram(s, t) {\n  if (s.length !== t.length) return false;\n  const c = new Map();\n  for (const ch of s) c.set(ch, (c.get(ch) || 0) + 1);\n  for (const ch of t) { if (!c.has(ch)) return false; c.set(ch, c.get(ch) - 1); if (c.get(ch) === 0) c.delete(ch); }\n  return c.size === 0;\n}\nconst result = isAnagram(data.s, data.t);`,
    testCases: [
      { input: '{"s":"anagram","t":"nagaram"}', expectedOutput: 'true' },
      { input: '{"s":"rat","t":"car"}', expectedOutput: 'false', isHidden: true },
    ],
  },
  {
    slug: 'product-of-array-except-self',
    title: 'Product of Array Except Self',
    difficulty: 'MEDIUM',
    topic: 'ARRAYS',
    tags: ['array', 'prefix-sum'],
    companies: BIG_TECH,
    description: 'Return array where each element is product of all nums except self.',
    fullDescription: `Given integer array \`nums\`, return array \`answer\` such that \`answer[i]\` equals the product of all elements except \`nums[i]\`. Solve **without division** in O(n).`,
    constraints: `2 <= nums.length <= 10^5\n-30 <= nums[i] <= 30`,
    examples: [
      { input: 'nums = [1,2,3,4]', output: '[24,12,8,6]' },
      { input: 'nums = [-1,1,0,-3,3]', output: '[0,0,9,0,0]' },
    ],
    edgeCases: ['Single zero makes most outputs zero', 'Multiple zeros yield all zeros'],
    hints: ['Division fails with zeros and forbidden.', 'Prefix products from left, suffix from right.', 'One pass output using running prefix then suffix.'],
    editorial: editorial('Compute total product and divide — invalid with zeros.', 'Explicit prefix and suffix arrays.', 'Reuse output array for prefix then multiply suffix.', 'O(n)', 'O(1) extra'),
    relatedSlugs: ['maximum-subarray', 'trapping-rain-water', 'contains-duplicate'],
    orderIndex: 13,
    py: `def product_except(nums):\n    n = len(nums)\n    res = [1] * n\n    p = 1\n    for i in range(n):\n        res[i] = p\n        p *= nums[i]\n    s = 1\n    for i in range(n - 1, -1, -1):\n        res[i] *= s\n        s *= nums[i]\n    return res\n\nresult = product_except(data["nums"])`,
    js: `function productExcept(nums) {\n  const n = nums.length, res = Array(n).fill(1);\n  let p = 1;\n  for (let i = 0; i < n; i++) { res[i] = p; p *= nums[i]; }\n  let s = 1;\n  for (let i = n - 1; i >= 0; i--) { res[i] *= s; s *= nums[i]; }\n  return res;\n}\nconst result = productExcept(data.nums);`,
    testCases: [
      { input: '{"nums":[1,2,3,4]}', expectedOutput: '[24,12,8,6]' },
      { input: '{"nums":[-1,1,0,-3,3]}', expectedOutput: '[0,0,9,0,0]', isHidden: true },
    ],
  },
  {
    slug: 'merge-sorted-array',
    title: 'Merge Sorted Arrays',
    difficulty: 'EASY',
    topic: 'ARRAYS',
    tags: ['array', 'two-pointers', 'sorting'],
    companies: ['Microsoft', 'Amazon'],
    description: 'Merge two sorted arrays into one sorted array.',
    fullDescription: `You are given two integer arrays \`nums1\` and \`nums2\`, sorted in **non-decreasing order**. Merge them into one sorted array and return it.`,
    constraints: `nums1.length, nums2.length >= 0`,
    examples: [
      { input: 'nums1 = [1,2,3], nums2 = [2,5,6]', output: '[1,2,2,3,5,6]' },
      { input: 'nums1 = [1], nums2 = []', output: '[1]' },
    ],
    edgeCases: ['One array empty', 'All elements of nums2 smaller than nums1'],
    hints: ['Two pointers at start of each array.', 'Append smaller head to result.', 'Drain remaining elements.'],
    editorial: editorial('Concatenate and sort.', 'Two-pointer merge into new array.', 'In-place merge from end if nums1 has buffer — variant.', 'O(n+m)', 'O(n+m)'),
    relatedSlugs: ['merge-intervals', 'merge-k-sorted-lists', 'binary-search'],
    orderIndex: 14,
    py: `def merge(a, b):\n    i = j = 0\n    res = []\n    while i < len(a) and j < len(b):\n        if a[i] <= b[j]:\n            res.append(a[i]); i += 1\n        else:\n            res.append(b[j]); j += 1\n    res.extend(a[i:]); res.extend(b[j:])\n    return res\n\nresult = merge(data["nums1"], data["nums2"])`,
    js: `function merge(a, b) {\n  const res = []; let i = 0, j = 0;\n  while (i < a.length && j < b.length) res.push(a[i] <= b[j] ? a[i++] : b[j++]);\n  return res.concat(a.slice(i), b.slice(j));\n}\nconst result = merge(data.nums1, data.nums2);`,
    testCases: [
      { input: '{"nums1":[1,2,3],"nums2":[2,5,6]}', expectedOutput: '[1,2,2,3,5,6]' },
      { input: '{"nums1":[1],"nums2":[]}', expectedOutput: '[1]', isHidden: true },
    ],
  },
  {
    slug: 'move-zeroes',
    title: 'Move Zeroes',
    difficulty: 'EASY',
    topic: 'ARRAYS',
    tags: ['array', 'two-pointers'],
    companies: ['Meta', 'Apple'],
    description: 'Move all zeros to the end while maintaining relative order of non-zeros.',
    fullDescription: `Given an integer array \`nums\`, move all \`0\`'s to the end while maintaining the relative order of non-zero elements. Return the modified array.`,
    constraints: `1 <= nums.length <= 10^4\n-2^31 <= nums[i] <= 2^31 - 1`,
    examples: [
      { input: 'nums = [0,1,0,3,12]', output: '[1,3,12,0,0]' },
      { input: 'nums = [0]', output: '[0]' },
    ],
    edgeCases: ['No zeros', 'All zeros'],
    hints: ['Slow/fast pointer to write position.', 'Swap non-zero forward.', 'Two-pass: fill non-zeros then zeros.'],
    editorial: editorial('Copy to new array.', 'Count non-zeros then place zeros.', 'In-place write index for non-zeros.', 'O(n)', 'O(1)'),
    relatedSlugs: ['remove-element', 'sort-colors', 'contains-duplicate'],
    orderIndex: 15,
    py: `nums = data["nums"]\nwrite = 0\nfor n in nums:\n    if n != 0:\n        nums[write] = n\n        write += 1\nfor i in range(write, len(nums)):\n    nums[i] = 0\nresult = nums`,
    js: `const nums = data.nums;\nlet w = 0;\nfor (const n of nums) if (n !== 0) nums[w++] = n;\nfor (let i = w; i < nums.length; i++) nums[i] = 0;\nconst result = nums;`,
    testCases: [
      { input: '{"nums":[0,1,0,3,12]}', expectedOutput: '[1,3,12,0,0]' },
      { input: '{"nums":[0,0,1]}', expectedOutput: '[1,0,0]', isHidden: true },
    ],
  },
  {
    slug: 'intersection-of-two-arrays-ii',
    title: 'Intersection of Two Arrays II',
    difficulty: 'EASY',
    topic: 'ARRAYS',
    tags: ['array', 'hash-table', 'sorting'],
    companies: ['Google', 'Yandex'],
    description: 'Return intersection of two arrays with multiplicity.',
    fullDescription: `Given two integer arrays \`nums1\` and \`nums2\`, return their intersection. Each element in the result must appear as many times as it shows in both arrays.`,
    constraints: `1 <= nums1.length, nums2.length <= 1000`,
    examples: [
      { input: 'nums1 = [1,2,2,1], nums2 = [2,2]', output: '[2,2]' },
      { input: 'nums1 = [4,9,5], nums2 = [9,4,8,9,5]', output: '[9,4] or [4,9]' },
    ],
    edgeCases: ['No common elements returns []', 'Duplicate counts limited by smaller frequency'],
    hints: ['Sort both and two-pointer match.', 'Hash map counts for nums1, decrement with nums2.', 'For sorted output, sort the result.'],
    editorial: editorial('Nested loops for each element.', 'Sort + two pointers.', 'Frequency map — O(n+m).', 'O(n+m)', 'O(n)'),
    relatedSlugs: ['intersection-of-two-arrays', 'contains-duplicate', 'two-sum'],
    orderIndex: 16,
    py: `from collections import Counter\nc1, c2 = Counter(data["nums1"]), Counter(data["nums2"])\nresult = sorted((c1 & c2).elements())`,
    js: `function intersect(a, b) {\n  const m = new Map();\n  for (const x of a) m.set(x, (m.get(x) || 0) + 1);\n  const res = [];\n  for (const x of b) if (m.get(x) > 0) { res.push(x); m.set(x, m.get(x) - 1); }\n  return res.sort((x, y) => x - y);\n}\nconst result = intersect(data.nums1, data.nums2);`,
    testCases: [
      { input: '{"nums1":[1,2,2,1],"nums2":[2,2]}', expectedOutput: '[2,2]' },
      { input: '{"nums1":[4,9,5],"nums2":[9,4,8,9,5]}', expectedOutput: '[4,9]', isHidden: true },
    ],
  },
  {
    slug: 'plus-one',
    title: 'Plus One',
    difficulty: 'EASY',
    topic: 'ARRAYS',
    tags: ['array', 'math'],
    companies: ['Google', 'Amazon'],
    description: 'Add one to a non-negative integer represented as digit array.',
    fullDescription: `You are given a large integer represented as an integer array \`digits\`, where each element is a digit. Increment the large integer by one and return the digit array.`,
    constraints: `1 <= digits.length <= 100\n0 <= digits[i] <= 9`,
    examples: [
      { input: 'digits = [1,2,3]', output: '[1,2,4]' },
      { input: 'digits = [9,9,9]', output: '[1,0,0,0]' },
    ],
    edgeCases: ['Trailing nines cause carry propagation', 'Single digit 9 becomes [1,0]'],
    hints: ['Start from least significant digit.', 'If digit < 9, increment and stop.', 'If all nines, prepend 1.'],
    editorial: editorial('Convert to string/bigint — may overflow in other langs.', 'Reverse, add carry, reverse back.', 'Single backward pass with early exit.', 'O(n)', 'O(1)'),
    relatedSlugs: ['add-binary', 'multiply-strings', 'plus-one'],
    orderIndex: 17,
    py: `digits = data["digits"]\nresult = None\nfor i in range(len(digits) - 1, -1, -1):\n    if digits[i] < 9:\n        digits[i] += 1\n        result = digits\n        break\nif result is None:\n    result = [1] + [0] * len(digits)`,
    js: `const digits = [...data.digits];\nlet result;\nfor (let i = digits.length - 1; i >= 0; i--) {\n  if (digits[i] < 9) { digits[i]++; result = digits; break; }\n  digits[i] = 0;\n}\nif (result === undefined) result = [1, ...digits.map(() => 0)];`,
    testCases: [
      { input: '{"digits":[1,2,3]}', expectedOutput: '[1,2,4]' },
      { input: '{"digits":[9,9,9]}', expectedOutput: '[1,0,0,0]', isHidden: true },
    ],
  },
  {
    slug: 'single-number',
    title: 'Single Number',
    difficulty: 'EASY',
    topic: 'ARRAYS',
    tags: ['array', 'bit-manipulation'],
    companies: BIG_TECH,
    description: 'Every element appears twice except one; find that one.',
    fullDescription: `Given a **non-empty** array \`nums\` where every element appears twice except for one, find that single one. Implement with linear time and O(1) extra space.`,
    constraints: `1 <= nums.length <= 3 * 10^4\n-3 * 10^4 <= nums[i] <= 3 * 10^4`,
    examples: [
      { input: 'nums = [2,2,1]', output: '1' },
      { input: 'nums = [4,1,2,1,2]', output: '4' },
    ],
    edgeCases: ['Single element array', 'Answer at any position'],
    hints: ['XOR of a number with itself is 0.', 'XOR is commutative — order does not matter.', 'XOR all numbers together.'],
    editorial: editorial('Hash map counts.', 'Set add/remove on seen.', 'XOR bitmask.', 'O(n)', 'O(1)'),
    relatedSlugs: ['single-number-ii', 'missing-number', 'contains-duplicate'],
    orderIndex: 18,
    py: `x = 0\nfor n in data["nums"]:\n    x ^= n\nresult = x`,
    js: `let x = 0;\nfor (const n of data.nums) x ^= n;\nconst result = x;`,
    testCases: [
      { input: '{"nums":[2,2,1]}', expectedOutput: '1' },
      { input: '{"nums":[4,1,2,1,2]}', expectedOutput: '4', isHidden: true },
    ],
  },
  {
    slug: 'majority-element',
    title: 'Majority Element',
    difficulty: 'EASY',
    topic: 'ARRAYS',
    tags: ['array', 'hash-table', 'divide-and-conquer'],
    companies: BIG_TECH,
    description: 'Find element appearing more than n/2 times (always exists).',
    fullDescription: `Given an array \`nums\` of size \`n\`, return the **majority element** (appears more than \`⌊n / 2⌋\` times). You may assume the majority element always exists.`,
    constraints: `n == nums.length\n1 <= n <= 5 * 10^4`,
    examples: [
      { input: 'nums = [3,2,3]', output: '3' },
      { input: 'nums = [2,2,1,1,1,2,2]', output: '2' },
    ],
    edgeCases: ['All same element', 'Majority at alternating positions'],
    hints: ['Hash map counts until count > n/2.', 'Sort middle index candidate — then verify.', 'Boyer-Moore voting algorithm.'],
    editorial: editorial('Count map.', 'Sort and return nums[n//2].', 'Boyer-Moore vote cancel.', 'O(n)', 'O(1)'),
    relatedSlugs: ['majority-element-ii', 'contains-duplicate', 'single-number'],
    orderIndex: 19,
    py: `cand = cnt = 0\nfor n in data["nums"]:\n    if cnt == 0:\n        cand, cnt = n, 1\n    elif n == cand:\n        cnt += 1\n    else:\n        cnt -= 1\nresult = cand`,
    js: `let cand = 0, cnt = 0;\nfor (const n of data.nums) {\n  if (cnt === 0) { cand = n; cnt = 1; }\n  else if (n === cand) cnt++;\n  else cnt--;\n}\nconst result = cand;`,
    testCases: [
      { input: '{"nums":[3,2,3]}', expectedOutput: '3' },
      { input: '{"nums":[2,2,1,1,1,2,2]}', expectedOutput: '2', isHidden: true },
    ],
  },
];
