import type { ProblemDef } from '../types.js';
import { editorial } from '../helpers.js';

const BIG_TECH = ['Google', 'Amazon', 'Meta', 'Microsoft'];

export const BATCH_03: ProblemDef[] = [
  {
    slug: 'invert-binary-tree',
    title: 'Invert Binary Tree',
    difficulty: 'EASY',
    topic: 'TREES',
    tags: ['tree', 'dfs', 'bfs'],
    companies: BIG_TECH,
    description: 'Invert a binary tree given as level-order array (null for missing nodes).',
    fullDescription: `Given the **root** of a binary tree as a level-order array (use \`null\` for missing children), invert the tree (mirror) and return the level-order representation.`,
    constraints: `Number of nodes in tree <= 100`,
    examples: [
      { input: 'root = [4,2,7,1,3,6,9]', output: '[4,7,2,9,6,3,1]' },
      { input: 'root = [2,1,3]', output: '[2,3,1]' },
    ],
    edgeCases: ['Empty tree []', 'Only root node'],
    hints: ['Swap left and right subtrees recursively.', 'BFS queue swapping children.', 'For array form, rebuild mirrored structure.'],
    editorial: editorial('Copy tree then swap — extra space.', 'Recursive DFS swap children.', 'Iterative BFS/DFS queue.', 'O(n)', 'O(h)'),
    relatedSlugs: ['same-tree', 'symmetric-tree', 'maximum-depth-of-binary-tree'],
    orderIndex: 20,
    py: `def invert_level(arr):\n    if not arr:\n        return []\n    res = list(arr)\n    for i in range(len(res)):\n        l, r = 2 * i + 1, 2 * i + 2\n        if l < len(res) and r < len(res):\n            res[l], res[r] = res[r], res[l]\n    return res\n\nresult = invert_level(data["root"])`,
    js: `function invertLevel(arr) {\n  if (!arr.length) return [];\n  const res = [...arr];\n  for (let i = 0; i < res.length; i++) {\n    const l = 2 * i + 1, r = 2 * i + 2;\n    if (l < res.length && r < res.length) [res[l], res[r]] = [res[r], res[l]];\n  }\n  return res;\n}\nconst result = invertLevel(data.root);`,
    testCases: [
      { input: '{"root":[4,2,7,1,3,6,9]}', expectedOutput: '[4,7,2,9,6,3,1]' },
      { input: '{"root":[]}', expectedOutput: '[]', isHidden: true },
    ],
  },
  {
    slug: 'maximum-depth-of-binary-tree',
    title: 'Maximum Depth of Binary Tree',
    difficulty: 'EASY',
    topic: 'TREES',
    tags: ['tree', 'dfs', 'bfs'],
    companies: BIG_TECH,
    description: 'Maximum depth (root to farthest leaf) for tree as nested array [val, left, right].',
    fullDescription: `Given a binary tree as nested JSON \`root\` (null if empty, else \`[value, left, right]\`), return its **maximum depth**.`,
    constraints: `Number of nodes <= 10^4`,
    examples: [
      { input: 'root = [3,[9,null,null],[20,[15,null,null],[7,null,null]]]', output: '3' },
      { input: 'root = [1,null,[2,null,null]]', output: '2' },
    ],
    edgeCases: ['null root depth 0', 'Skewed tree depth n'],
    hints: ['Depth is 1 + max(left, right).', 'BFS level count works too.', 'Base case: null node returns 0.'],
    editorial: editorial('Track all root-to-leaf paths.', 'DFS recursion on children.', 'BFS increment level.', 'O(n)', 'O(h)'),
    relatedSlugs: ['minimum-depth-of-binary-tree', 'balanced-binary-tree', 'invert-binary-tree'],
    orderIndex: 21,
    py: `def depth(node):\n    if node is None:\n        return 0\n    _, left, right = node\n    return 1 + max(depth(left), depth(right))\n\nresult = depth(data["root"])`,
    js: `function depth(node) {\n  if (node == null) return 0;\n  const [, l, r] = node;\n  return 1 + Math.max(depth(l), depth(r));\n}\nconst result = depth(data.root);`,
    testCases: [
      { input: '{"root":[3,[9,null,null],[20,[15,null,null],[7,null,null]]]}', expectedOutput: '3' },
      { input: '{"root":null}', expectedOutput: '0', isHidden: true },
    ],
  },
  {
    slug: 'same-tree',
    title: 'Same Tree',
    difficulty: 'EASY',
    topic: 'TREES',
    tags: ['tree', 'dfs', 'bfs'],
    companies: ['Amazon', 'Bloomberg'],
    description: 'Check if two binary trees (nested JSON) are identical.',
    fullDescription: `Given the roots of two binary trees \`p\` and \`q\` in nested JSON form, return \`true\` if they are the same tree.`,
    constraints: `Number of nodes in both trees <= 100`,
    examples: [
      { input: 'p = [1,[2,null,null],null], q = [1,[2,null,null],null]', output: 'true' },
      { input: 'p = [1,[2,null,null],null], q = [1,null,[2,null,null]]', output: 'false' },
    ],
    edgeCases: ['Both null is true', 'One null false'],
    hints: ['Compare values and recurse both sides.', 'Short-circuit on first mismatch.', 'Iterative stack of node pairs.'],
    editorial: editorial('Serialize and compare strings.', 'Recursive structural compare.', 'BFS with paired queues.', 'O(n)', 'O(h)'),
    relatedSlugs: ['symmetric-tree', 'subtree-of-another-tree', 'invert-binary-tree'],
    orderIndex: 22,
    py: `def same(a, b):\n    if a is None and b is None:\n        return True\n    if a is None or b is None:\n        return False\n    return a[0] == b[0] and same(a[1], b[1]) and same(a[2], b[2])\n\nresult = same(data["p"], data["q"])`,
    js: `function same(a, b) {\n  if (a == null && b == null) return true;\n  if (a == null || b == null) return false;\n  return a[0] === b[0] && same(a[1], b[1]) && same(a[2], b[2]);\n}\nconst result = same(data.p, data.q);`,
    testCases: [
      { input: '{"p":[1,[2,null,null],null],"q":[1,[2,null,null],null]}', expectedOutput: 'true' },
      { input: '{"p":[1,[2,null,null],null],"q":[1,null,[2,null,null]]}', expectedOutput: 'false', isHidden: true },
    ],
  },
  {
    slug: 'binary-tree-level-order-traversal',
    title: 'Binary Tree Level Order Traversal',
    difficulty: 'MEDIUM',
    topic: 'TREES',
    tags: ['tree', 'bfs'],
    companies: BIG_TECH,
    description: 'Return level-order traversal of binary tree (nested JSON).',
    fullDescription: `Given the \`root\` of a binary tree in nested JSON, return the **level-order** traversal as array of levels.`,
    constraints: `Number of nodes <= 2000`,
    examples: [
      { input: 'root = [3,[9,null,null],[20,[15,null,null],[7,null,null]]]', output: '[[3],[9,20],[15,7]]' },
      { input: 'root = [1]', output: '[[1]]' },
    ],
    edgeCases: ['Empty tree returns []', 'Only left children'],
    hints: ['BFS with queue; track level size.', 'DFS with depth index to build levels.', 'Use null markers for array roots — nested form avoids that.'],
    editorial: editorial('DFS collect all nodes then group — awkward.', 'BFS queue per level.', 'DFS with depth list append.', 'O(n)', 'O(n)'),
    relatedSlugs: ['binary-tree-zigzag-level-order', 'maximum-depth-of-binary-tree', 'right-side-view'],
    orderIndex: 23,
    py: `from collections import deque\n\ndef level_order(root):\n    if root is None:\n        return []\n    q = deque([root])\n    out = []\n    while q:\n        level = []\n        for _ in range(len(q)):\n            node = q.popleft()\n            level.append(node[0])\n            if node[1]: q.append(node[1])\n            if node[2]: q.append(node[2])\n        out.append(level)\n    return out\n\nresult = level_order(data["root"])`,
    js: `function levelOrder(root) {\n  if (root == null) return [];\n  const q = [root], out = [];\n  while (q.length) {\n    const level = [], size = q.length;\n    for (let i = 0; i < size; i++) {\n      const [v, l, r] = q.shift();\n      level.push(v);\n      if (l) q.push(l);\n      if (r) q.push(r);\n    }\n    out.push(level);\n  }\n  return out;\n}\nconst result = levelOrder(data.root);`,
    testCases: [
      { input: '{"root":[3,[9,null,null],[20,[15,null,null],[7,null,null]]]}', expectedOutput: '[[3],[9,20],[15,7]]' },
      { input: '{"root":null}', expectedOutput: '[]', isHidden: true },
    ],
  },
  {
    slug: 'validate-binary-search-tree',
    title: 'Validate Binary Search Tree',
    difficulty: 'MEDIUM',
    topic: 'TREES',
    tags: ['tree', 'dfs', 'bst'],
    companies: BIG_TECH,
    description: 'Validate if nested JSON tree satisfies BST property.',
    fullDescription: `Given the \`root\` of a binary tree in nested JSON, determine if it is a valid **binary search tree** (all left subtree < node < all right subtree).`,
    constraints: `Number of nodes <= 10^4\n-2^31 <= Node.val <= 2^31 - 1`,
    examples: [
      { input: 'root = [2,[1,null,null],[3,null,null]]', output: 'true' },
      { input: 'root = [5,[1,null,null],[4,[3,null,null],[6,null,null]]]', output: 'false' },
    ],
    edgeCases: ['Duplicate values invalid for strict BST', 'Integer overflow on bounds'],
    hints: ['Inorder should be strictly increasing.', 'Pass min/max bounds down recursion.', 'Avoid only comparing parent-child.'],
    editorial: editorial('Check each node vs immediate children only — wrong.', 'Inorder traversal compare prev.', 'DFS with (min, max) bounds.', 'O(n)', 'O(h)'),
    relatedSlugs: ['kth-smallest-element-in-a-bst', 'lowest-common-ancestor-of-a-binary-search-tree', 'insert-into-a-binary-search-tree'],
    orderIndex: 24,
    py: `def valid(node, lo=float('-inf'), hi=float('inf')):\n    if node is None:\n        return True\n    v, l, r = node\n    if not (lo < v < hi):\n        return False\n    return valid(l, lo, v) and valid(r, v, hi)\n\nresult = valid(data["root"])`,
    js: `function valid(node, lo = -Infinity, hi = Infinity) {\n  if (node == null) return true;\n  const [v, l, r] = node;\n  if (!(lo < v && v < hi)) return false;\n  return valid(l, lo, v) && valid(r, v, hi);\n}\nconst result = valid(data.root);`,
    testCases: [
      { input: '{"root":[2,[1,null,null],[3,null,null]]}', expectedOutput: 'true' },
      { input: '{"root":[5,[1,null,null],[4,[3,null,null],[6,null,null]]]}', expectedOutput: 'false', isHidden: true },
    ],
  },
  {
    slug: 'lowest-common-ancestor-of-bst',
    title: 'Lowest Common Ancestor of BST',
    difficulty: 'EASY',
    topic: 'TREES',
    tags: ['tree', 'bst', 'dfs'],
    companies: BIG_TECH,
    description: 'Find LCA of two nodes p and q in a BST (nested JSON).',
    fullDescription: `Given a BST as nested JSON \`root\` and values \`p\` and \`q\`, return the **lowest common ancestor** node value.`,
    constraints: `Number of nodes <= 10^5\nAll values unique`,
    examples: [
      { input: 'root = [6,[2,[0,null,null],[4,[3,null,null],[5,null,null]]],[8,[7,null,null],[9,null,null]]], p=2, q=8', output: '6' },
      { input: 'root = [6,[2,[0,null,null],[4,[3,null,null],[5,null,null]]],[8,[7,null,null],[9,null,null]]], p=2, q=4', output: '2' },
    ],
    edgeCases: ['p or q is root', 'p and q on same side'],
    hints: ['If both smaller, go left; both larger, go right.', 'First split point is LCA.', 'General tree needs parent map — BST simpler.'],
    editorial: editorial('Store path from root for both.', 'Recursive search returning node if found.', 'BST compare p,q with current.', 'O(h)', 'O(h)'),
    relatedSlugs: ['lowest-common-ancestor-of-a-binary-tree', 'validate-binary-search-tree', 'search-in-a-binary-search-tree'],
    orderIndex: 25,
    py: `def lca(node, p, q):\n    if node is None:\n        return None\n    v, l, r = node\n    if p < v and q < v:\n        return lca(l, p, q)\n    if p > v and q > v:\n        return lca(r, p, q)\n    return v\n\nresult = lca(data["root"], data["p"], data["q"])`,
    js: `function lca(node, p, q) {\n  if (node == null) return null;\n  const [v, l, r] = node;\n  if (p < v && q < v) return lca(l, p, q);\n  if (p > v && q > v) return lca(r, p, q);\n  return v;\n}\nconst result = lca(data.root, data.p, data.q);`,
    testCases: [
      { input: '{"root":[6,[2,[0,null,null],[4,[3,null,null],[5,null,null]]],[8,[7,null,null],[9,null,null]]],"p":2,"q":8}', expectedOutput: '6' },
      { input: '{"root":[6,[2,[0,null,null],[4,[3,null,null],[5,null,null]]],[8,[7,null,null],[9,null,null]]],"p":2,"q":4}', expectedOutput: '2', isHidden: true },
    ],
  },
  {
    slug: 'subtree-of-another-tree',
    title: 'Subtree of Another Tree',
    difficulty: 'EASY',
    topic: 'TREES',
    tags: ['tree', 'dfs'],
    companies: ['Meta', 'Amazon'],
    description: 'Check if subRoot is a subtree of root (nested JSON).',
    fullDescription: `Given \`root\` and \`subRoot\` binary trees in nested JSON, return \`true\` if \`subRoot\` is a subtree of \`root\`.`,
    constraints: `Number of nodes in trees <= 2000`,
    examples: [
      { input: 'root = [3,[4,null,null],[5,null,null]], subRoot = [4,null,null]', output: 'true' },
      { input: 'root = [3,[4,null,null],[5,null,null]], subRoot = [2,null,null]', output: 'false' },
    ],
    edgeCases: ['subRoot null is always true', 'Identical trees'],
    hints: ['When roots match, use same-tree check.', 'Traverse every node in root as candidate.', 'Serialize both with null markers — compare strings.'],
    editorial: editorial('Compare all nodes O(n*m).', 'DFS match at each node.', 'Tree serialization hashing — advanced.', 'O(n*m)', 'O(h)'),
    relatedSlugs: ['same-tree', 'invert-binary-tree', 'maximum-depth-of-binary-tree'],
    orderIndex: 26,
    py: `def same(a,b):\n    if a is None and b is None: return True\n    if a is None or b is None: return False\n    return a[0]==b[0] and same(a[1],b[1]) and same(a[2],b[2])\ndef is_sub(root, sub):\n    if sub is None: return True\n    if root is None: return False\n    return same(root, sub) or is_sub(root[1], sub) or is_sub(root[2], sub)\nresult = is_sub(data["root"], data["subRoot"])`,
    js: `function same(a,b){if(a==null&&b==null)return true;if(a==null||b==null)return false;return a[0]===b[0]&&same(a[1],b[1])&&same(a[2],b[2]);}\nfunction isSub(r,s){if(s==null)return true;if(r==null)return false;return same(r,s)||isSub(r[1],s)||isSub(r[2],s);}\nconst result = isSub(data.root, data.subRoot);`,
    testCases: [
      { input: '{"root":[3,[4,null,null],[5,null,null]],"subRoot":[4,null,null]}', expectedOutput: 'true' },
      { input: '{"root":[3,[4,null,null],[5,null,null]],"subRoot":[2,null,null]}', expectedOutput: 'false', isHidden: true },
    ],
  },
  {
    slug: 'diameter-of-binary-tree',
    title: 'Diameter of Binary Tree',
    difficulty: 'EASY',
    topic: 'TREES',
    tags: ['tree', 'dfs'],
    companies: ['Google', 'Facebook'],
    description: 'Length of longest path between any two nodes in tree.',
    fullDescription: `Given nested JSON \`root\`, return the **diameter** (number of edges on longest path).`,
    constraints: `Number of nodes <= 10^4`,
    examples: [
      { input: 'root = [1,[2,[4,null,null],[5,null,null]],[3,null,null]]', output: '3' },
      { input: 'root = [1,[2,null,null],null]', output: '1' },
    ],
    edgeCases: ['Single node diameter 0', 'Diameter may not pass root'],
    hints: ['Longest path may bend at a node.', 'For each node, combine left+right depths.', 'Track global max during height DFS.'],
    editorial: editorial('Try all pairs of nodes — O(n^2).', 'Repeated height computations.', 'One DFS height with diameter update.', 'O(n)', 'O(h)'),
    relatedSlugs: ['maximum-depth-of-binary-tree', 'binary-tree-maximum-path-sum', 'balanced-binary-tree'],
    orderIndex: 27,
    py: `best = 0\ndef height(node):\n    global best\n    if node is None:\n        return 0\n    l = height(node[1])\n    r = height(node[2])\n    best = max(best, l + r)\n    return 1 + max(l, r)\nheight(data["root"])\nresult = best`,
    js: `let best = 0;\nfunction height(node) {\n  if (node == null) return 0;\n  const l = height(node[1]), r = height(node[2]);\n  best = Math.max(best, l + r);\n  return 1 + Math.max(l, r);\n}\nheight(data.root);\nconst result = best;`,
    testCases: [
      { input: '{"root":[1,[2,[4,null,null],[5,null,null]],[3,null,null]]}', expectedOutput: '3' },
      { input: '{"root":[1,[2,null,null],null]}', expectedOutput: '1', isHidden: true },
    ],
  },
  {
    slug: 'balanced-binary-tree',
    title: 'Balanced Binary Tree',
    difficulty: 'EASY',
    topic: 'TREES',
    tags: ['tree', 'dfs'],
    companies: ['Amazon', 'Bloomberg'],
    description: 'Return true if tree height difference of subtrees is at most 1 everywhere.',
    fullDescription: `Given nested JSON \`root\`, return whether the tree is **height-balanced**.`,
    constraints: `Number of nodes <= 10^4`,
    examples: [
      { input: 'root = [3,[9,null,null],[20,null,[7,null,null]]]', output: 'true' },
      { input: 'root = [1,[2,[3,[4,[5,null,null],null],null],null],null]', output: 'false' },
    ],
    edgeCases: ['Empty tree balanced', 'Skewed tree unbalanced'],
    hints: ['Compare left and right heights at each node.', 'If imbalance > 1 return sentinel.', 'Combine height check with balance flag.'],
    editorial: editorial('Recompute heights repeatedly.', 'Bottom-up return -1 if unbalanced.', 'Post-order height with early exit.', 'O(n)', 'O(h)'),
    relatedSlugs: ['maximum-depth-of-binary-tree', 'diameter-of-binary-tree', 'validate-binary-search-tree'],
    orderIndex: 28,
    py: `def check(node):\n    if node is None:\n        return 0\n    l, r = check(node[1]), check(node[2])\n    if l < 0 or r < 0 or abs(l - r) > 1:\n        return -1\n    return 1 + max(l, r)\nresult = check(data["root"]) >= 0`,
    js: `function check(node) {\n  if (node == null) return 0;\n  const l = check(node[1]), r = check(node[2]);\n  if (l < 0 || r < 0 || Math.abs(l - r) > 1) return -1;\n  return 1 + Math.max(l, r);\n}\nconst result = check(data.root) >= 0;`,
    testCases: [
      { input: '{"root":[3,[9,null,null],[20,null,[7,null,null]]]}', expectedOutput: 'true' },
      { input: '{"root":[1,[2,[3,[4,[5,null,null],null],null],null],null]}', expectedOutput: 'false', isHidden: true },
    ],
  },
  {
    slug: 'path-sum',
    title: 'Path Sum',
    difficulty: 'EASY',
    topic: 'TREES',
    tags: ['tree', 'dfs'],
    companies: BIG_TECH,
    description: 'Return true if root-to-leaf path sums to target.',
    fullDescription: `Given nested JSON \`root\` and integer \`targetSum\`, return \`true\` if there is a **root-to-leaf** path such that the sum equals \`targetSum\`.`,
    constraints: `Number of nodes <= 5000`,
    examples: [
      { input: 'root = [5,[4,[11,[7,null,null],[2,null,null]],null],[8,[13,null,null],[4,null,[1,null,null]]]], targetSum = 22', output: 'true' },
      { input: 'root = [1,[2,null,null],null], targetSum = 1', output: 'false' },
    ],
    edgeCases: ['Negative values allowed', 'Leaf must be endpoint — not partial path'],
    hints: ['Subtract node value from target at each step.', 'At leaf, remaining target should be 0.', 'DFS both children.'],
    editorial: editorial('Store all root-to-leaf sums.', 'Recursive DFS with remaining sum.', 'Iterative stack with (node, sum).', 'O(n)', 'O(h)'),
    relatedSlugs: ['path-sum-ii', 'binary-tree-maximum-path-sum', 'maximum-depth-of-binary-tree'],
    orderIndex: 29,
    py: `def has_path(node, rem):\n    if node is None:\n        return False\n    v, l, r = node\n    if l is None and r is None:\n        return rem == v\n    return has_path(l, rem - v) or has_path(r, rem - v)\n\nresult = has_path(data["root"], data["targetSum"])`,
    js: `function hasPath(node, rem) {\n  if (node == null) return false;\n  const [v, l, r] = node;\n  if (l == null && r == null) return rem === v;\n  return hasPath(l, rem - v) || hasPath(r, rem - v);\n}\nconst result = hasPath(data.root, data.targetSum);`,
    testCases: [
      { input: '{"root":[5,[4,[11,[7,null,null],[2,null,null]],null],[8,[13,null,null],[4,null,[1,null,null]]]],"targetSum":22}', expectedOutput: 'true' },
      { input: '{"root":[1,[2,null,null],null],"targetSum":1}', expectedOutput: 'false', isHidden: true },
    ],
  },
];
