import type { ProblemDef } from '../types.js';
import { editorial } from '../helpers.js';

const BIG_TECH = ['Google', 'Amazon', 'Meta', 'Microsoft'];

export const BATCH_05: ProblemDef[] = [
  {
    slug: 'subsets',
    title: 'Subsets',
    difficulty: 'MEDIUM',
    topic: 'ARRAYS',
    tags: ['array', 'backtracking', 'bit-manipulation'],
    companies: BIG_TECH,
    description: 'Return all possible subsets of distinct integers.',
    fullDescription: `Given an integer array \`nums\` of **unique** elements, return all possible subsets (the power set). The solution set must not contain duplicate subsets.`,
    constraints: `1 <= nums.length <= 10\n-10 <= nums[i] <= 10`,
    examples: [
      { input: 'nums = [1,2,3]', output: '[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]' },
      { input: 'nums = [0]', output: '[[],[0]]' },
    ],
    edgeCases: ['Empty subset always included', 'Order of subsets may vary — compare as sets in tests'],
    hints: ['For each element, choose in or out.', 'Backtrack building current subset.', 'Iterative: double subsets adding nums[i].'],
    editorial: editorial('Recursion with include/exclude.', 'Backtracking push/pop.', 'Iterative bitmask or cascade.', 'O(n*2^n)', 'O(n)'),
    relatedSlugs: ['subsets-ii', 'permutations', 'combination-sum'],
    orderIndex: 40,
    py: `nums = sorted(data["nums"])\nres = [[]]\nfor n in nums:\n    res += [s + [n] for s in res]\nresult = res`,
    js: `const nums = [...data.nums].sort((a, b) => a - b);\nlet res = [[]];\nfor (const n of nums) res = res.concat(res.map((s) => [...s, n]));\nconst result = res;`,
    testCases: [
      { input: '{"nums":[1,2,3]}', expectedOutput: '[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]' },
      { input: '{"nums":[0]}', expectedOutput: '[[],[0]]', isHidden: true },
    ],
  },
  {
    slug: 'permutations',
    title: 'Permutations',
    difficulty: 'MEDIUM',
    topic: 'ARRAYS',
    tags: ['array', 'backtracking'],
    companies: BIG_TECH,
    description: 'Return all permutations of distinct integers.',
    fullDescription: `Given an array \`nums\` of distinct integers, return all possible **permutations**.`,
    constraints: `1 <= nums.length <= 6`,
    examples: [
      { input: 'nums = [1,2,3]', output: '[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]' },
      { input: 'nums = [0,1]', output: '[[0,1],[1,0]]' },
    ],
    edgeCases: ['Single element', 'Two elements swap'],
    hints: ['Use used[] array in backtracking.', 'Swap nums[i] into position i.', 'Python itertools permutations for reference.'],
    editorial: editorial('Heaps algorithm or next_permutation.', 'Backtrack choose unused.', 'Swap-based DFS.', 'O(n*n!)', 'O(n)'),
    relatedSlugs: ['permutations-ii', 'next-permutation', 'combination-sum'],
    orderIndex: 41,
    py: `def backtrack(path, used):\n    if len(path) == len(nums):\n        out.append(path[:])\n        return\n    for i, n in enumerate(nums):\n        if used[i]: continue\n        used[i] = True\n        path.append(n)\n        backtrack(path, used)\n        path.pop()\n        used[i] = False\nnums = data["nums"]\nout = []\nbacktrack([], [False]*len(nums))\nresult = out`,
    js: `const nums = data.nums;\nconst out = [];\nfunction bt(path, used) {\n  if (path.length === nums.length) { out.push([...path]); return; }\n  for (let i = 0; i < nums.length; i++) {\n    if (used[i]) continue;\n    used[i] = true; path.push(nums[i]);\n    bt(path, used);\n    path.pop(); used[i] = false;\n  }\n}\nbt([], Array(nums.length).fill(false));\nconst result = out;`,
    testCases: [
      { input: '{"nums":[1,2,3]}', expectedOutput: '[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]' },
      { input: '{"nums":[0,1]}', expectedOutput: '[[0,1],[1,0]]', isHidden: true },
    ],
  },
  {
    slug: 'combination-sum',
    title: 'Combination Sum',
    difficulty: 'MEDIUM',
    topic: 'ARRAYS',
    tags: ['array', 'backtracking'],
    companies: BIG_TECH,
    description: 'Combinations summing to target (reuse candidates).',
    fullDescription: `Given distinct integers \`candidates\` and \`target\`, return all unique combinations where chosen numbers sum to \`target\`. The **same** number may be used unlimited times.`,
    constraints: `1 <= candidates.length <= 30\n2 <= candidates[i] <= 40\nAll elements distinct`,
    examples: [
      { input: 'candidates = [2,3,6,7], target = 7', output: '[[2,2,3],[7]]' },
      { input: 'candidates = [2,3,5], target = 8', output: '[[2,2,2,2],[2,3,3],[3,5]]' },
    ],
    edgeCases: ['No combination returns []', 'Single candidate equals target'],
    hints: ['Sort candidates; stop when sum exceeds target.', 'Backtrack with start index to avoid permutations.', 'Subtract candidate and recurse same index.'],
    editorial: editorial('Generate all multisets — huge.', 'Backtracking with pruning.', 'DP for count only — variant.', 'O(2^target) practical with prune', 'O(target)'),
    relatedSlugs: ['combination-sum-ii', 'subsets', 'coin-change'],
    orderIndex: 42,
    py: `cands, target = sorted(data["candidates"]), data["target"]\nout = []\ndef dfs(i, rem, path):\n    if rem == 0:\n        out.append(path[:]); return\n    if rem < 0 or i == len(cands):\n        return\n    path.append(cands[i])\n    dfs(i, rem - cands[i], path)\n    path.pop()\n    dfs(i + 1, rem, path)\ndfs(0, target, [])\nresult = out`,
    js: `const cands = [...data.candidates].sort((a,b)=>a-b), target = data.target;\nconst out = [];\nfunction dfs(i, rem, path) {\n  if (rem === 0) { out.push([...path]); return; }\n  if (rem < 0 || i === cands.length) return;\n  path.push(cands[i]); dfs(i, rem - cands[i], path); path.pop();\n  dfs(i + 1, rem, path);\n}\ndfs(0, target, []);\nconst result = out;`,
    testCases: [
      { input: '{"candidates":[2,3,6,7],"target":7}', expectedOutput: '[[2,2,3],[7]]' },
      { input: '{"candidates":[2,3,5],"target":8}', expectedOutput: '[[2,2,2,2],[2,3,3],[3,5]]', isHidden: true },
    ],
  },
  {
    slug: 'letter-combinations-of-a-phone-number',
    title: 'Letter Combinations of a Phone Number',
    difficulty: 'MEDIUM',
    topic: 'STRINGS',
    tags: ['string', 'backtracking', 'hash-table'],
    companies: BIG_TECH,
    description: 'All letter combinations from phone digit string.',
    fullDescription: `Given a string containing digits from \`2-9\`, return all possible letter combinations that the number could represent (phone keypad mapping).`,
    constraints: `0 <= digits.length <= 4\ndigits[i] is digit 2-9.`,
    examples: [
      { input: 'digits = "23"', output: '["ad","ae","af","bd","be","bf","cd","ce","cf"]' },
      { input: 'digits = ""', output: '[]' },
    ],
    edgeCases: ['Empty digits returns []', 'Single digit returns 3-4 letters'],
    hints: ['Map digit to letters.', 'Backtrack building string char by char.', 'Cartesian product of letter lists.'],
    editorial: editorial('Nested loops by digit count — limited.', 'BFS/DFS build combinations.', 'Backtracking standard.', 'O(4^n)', 'O(n)'),
    relatedSlugs: ['generate-parentheses', 'permutations', 'subsets'],
    orderIndex: 43,
    py: `MAP = {"2":"abc","3":"def","4":"ghi","5":"jkl","6":"mno","7":"pqrs","8":"tuv","9":"wxyz"}\ndigits = data["digits"]\nif not digits:\n    result = []\nelse:\n    out = []\n    def dfs(i, path):\n        if i == len(digits):\n            out.append("".join(path)); return\n        for c in MAP[digits[i]]:\n            path.append(c); dfs(i+1, path); path.pop()\n    dfs(0, [])\n    result = out`,
    js: `const MAP = {2:"abc",3:"def",4:"ghi",5:"jkl",6:"mno",7:"pqrs",8:"tuv",9:"wxyz"};\nconst digits = data.digits;\nif (!digits) { result = []; } else {\n  const out = [];\n  function dfs(i, path) {\n    if (i === digits.length) { out.push(path.join("")); return; }\n    for (const c of MAP[digits[i]]) { path.push(c); dfs(i+1, path); path.pop(); }\n  }\n  dfs(0, []);\n  result = out;\n}`,
    testCases: [
      { input: '{"digits":"23"}', expectedOutput: '["ad","ae","af","bd","be","bf","cd","ce","cf"]' },
      { input: '{"digits":""}', expectedOutput: '[]', isHidden: true },
    ],
  },
  {
    slug: 'search-in-rotated-sorted-array',
    title: 'Search in Rotated Sorted Array',
    difficulty: 'MEDIUM',
    topic: 'BINARY_SEARCH',
    tags: ['array', 'binary-search'],
    companies: BIG_TECH,
    description: 'Search target in rotated sorted array without duplicates.',
    fullDescription: `Given rotated sorted array \`nums\` and \`target\`, return index of \`target\` or \`-1\`. All values are **unique**.`,
    constraints: `1 <= nums.length <= 5000`,
    examples: [
      { input: 'nums = [4,5,6,7,0,1,2], target = 0', output: '4' },
      { input: 'nums = [4,5,6,7,0,1,2], target = 3', output: '-1' },
    ],
    edgeCases: ['Not rotated — normal binary search', 'Target at pivot'],
    hints: ['One half of mid is always sorted.', 'Check if target in sorted half.', 'Adjust lo/hi accordingly.'],
    editorial: editorial('Find pivot then two binary searches.', 'Modified binary search one pass.', 'Same with recursion.', 'O(log n)', 'O(1)'),
    relatedSlugs: ['find-minimum-in-rotated-sorted-array', 'binary-search', 'search-a-2d-matrix'],
    orderIndex: 44,
    py: `nums, target = data["nums"], data["target"]\nlo, hi = 0, len(nums) - 1\nans = -1\nwhile lo <= hi:\n    mid = (lo + hi) // 2\n    if nums[mid] == target:\n        ans = mid; break\n    if nums[lo] <= nums[mid]:\n        if nums[lo] <= target < nums[mid]:\n            hi = mid - 1\n        else:\n            lo = mid + 1\n    else:\n        if nums[mid] < target <= nums[hi]:\n            lo = mid + 1\n        else:\n            hi = mid - 1\nresult = ans`,
    js: `const { nums, target } = data;\nlet lo = 0, hi = nums.length - 1, ans = -1;\nwhile (lo <= hi) {\n  const mid = (lo + hi) >> 1;\n  if (nums[mid] === target) { ans = mid; break; }\n  if (nums[lo] <= nums[mid]) {\n    if (nums[lo] <= target && target < nums[mid]) hi = mid - 1; else lo = mid + 1;\n  } else {\n    if (nums[mid] < target && target <= nums[hi]) lo = mid + 1; else hi = mid - 1;\n  }\n}\nconst result = ans;`,
    testCases: [
      { input: '{"nums":[4,5,6,7,0,1,2],"target":0}', expectedOutput: '4' },
      { input: '{"nums":[4,5,6,7,0,1,2],"target":3}', expectedOutput: '-1', isHidden: true },
    ],
  },
  {
    slug: 'koko-eating-bananas',
    title: 'Koko Eating Bananas',
    difficulty: 'MEDIUM',
    topic: 'BINARY_SEARCH',
    tags: ['array', 'binary-search'],
    companies: ['Google', 'Facebook', 'Amazon'],
    description: 'Minimum eating speed k to finish piles within h hours.',
    fullDescription: `Koko loves bananas. Given pile array \`piles\` and \`h\` hours, choose hourly eating speed \`k\` (minimum integer) to eat all bananas within \`h\` hours.`,
    constraints: `1 <= piles.length <= 10^4\nh >= piles.length`,
    examples: [
      { input: 'piles = [3,6,7,11], h = 8', output: '4' },
      { input: 'piles = [30,11,23,4,20], h = 5', output: '30' },
    ],
    edgeCases: ['h equals piles.length — must eat max pile in one hour', 'Large piles need high k'],
    hints: ['Higher k means fewer hours — monotonic.', 'Binary search k from 1 to max(piles).', 'hours(k) = sum(ceil(pile/k)).'],
    editorial: editorial('Try all k from 1 to max — O(n*max).', 'Binary search answer space.', 'Same with prefix sums — no better.', 'O(n log max)', 'O(1)'),
    relatedSlugs: ['binary-search', 'capacity-to-ship-packages-within-d-days', 'split-array-largest-sum'],
    orderIndex: 45,
    py: `import math\npiles, h = data["piles"], data["h"]\ndef hours(k):\n    return sum(math.ceil(p / k) for p in piles)\nlo, hi = 1, max(piles)\nwhile lo < hi:\n    mid = (lo + hi) // 2\n    if hours(mid) <= h:\n        hi = mid\n    else:\n        lo = mid + 1\nresult = lo`,
    js: `const { piles, h } = data;\nconst hours = (k) => piles.reduce((s, p) => s + Math.ceil(p / k), 0);\nlet lo = 1, hi = Math.max(...piles);\nwhile (lo < hi) {\n  const mid = (lo + hi) >> 1;\n  if (hours(mid) <= h) hi = mid; else lo = mid + 1;\n}\nconst result = lo;`,
    testCases: [
      { input: '{"piles":[3,6,7,11],"h":8}', expectedOutput: '4' },
      { input: '{"piles":[30,11,23,4,20],"h":5}', expectedOutput: '30', isHidden: true },
    ],
  },
  {
    slug: 'assign-cookies',
    title: 'Assign Cookies',
    difficulty: 'EASY',
    topic: 'GREEDY',
    tags: ['greedy', 'array', 'sorting'],
    companies: ['Amazon'],
    description: 'Maximize number of content children with cookie sizes.',
    fullDescription: `Given \`g\` (children greed factors) and \`s\` (cookie sizes), maximize number of children where cookie size >= greed. Each child at most one cookie.`,
    constraints: `1 <= g.length, s.length <= 3 * 10^4`,
    examples: [
      { input: 'g = [1,2,3], s = [1,1]', output: '1' },
      { input: 'g = [1,2], s = [1,2,3]', output: '2' },
    ],
    edgeCases: ['No cookies satisfies anyone', 'Sort both arrays first'],
    hints: ['Sort g and s.', 'Try smallest cookie that satisfies child.', 'Two pointers greedy.'],
    editorial: editorial('Try all assignments — exponential.', 'Sort + two pointers.', 'Same greedy optimal for matching.', 'O(n log n)', 'O(1)'),
    relatedSlugs: ['jump-game', 'best-time-to-buy-and-sell-stock', 'merge-intervals'],
    orderIndex: 46,
    py: `g = sorted(data["g"])\ns = sorted(data["s"])\ni = j = cnt = 0\nwhile i < len(g) and j < len(s):\n    if s[j] >= g[i]:\n        cnt += 1\n        i += 1\n    j += 1\nresult = cnt`,
    js: `const g = [...data.g].sort((a,b)=>a-b);\nconst s = [...data.s].sort((a,b)=>a-b);\nlet i = 0, j = 0, cnt = 0;\nwhile (i < g.length && j < s.length) {\n  if (s[j] >= g[i]) { cnt++; i++; }\n  j++;\n}\nconst result = cnt;`,
    testCases: [
      { input: '{"g":[1,2,3],"s":[1,1]}', expectedOutput: '1' },
      { input: '{"g":[1,2],"s":[1,2,3]}', expectedOutput: '2', isHidden: true },
    ],
  },
  {
    slug: 'merge-k-sorted-lists',
    title: 'Merge K Sorted Lists',
    difficulty: 'HARD',
    topic: 'LINKED_LISTS',
    tags: ['linked-list', 'heap', 'divide-and-conquer'],
    companies: BIG_TECH,
    description: 'Merge k sorted arrays into one sorted array.',
    fullDescription: `You are given array \`lists\` of sorted integer arrays. Merge all into one sorted array and return it.`,
    constraints: `k == lists.length\n0 <= k <= 10^4`,
    examples: [
      { input: 'lists = [[1,4,5],[1,3,4],[2,6]]', output: '[1,1,2,3,4,4,5,6]' },
      { input: 'lists = []', output: '[]' },
    ],
    edgeCases: ['Empty lists input', 'Some lists empty'],
    hints: ['Concatenate and sort — O(N log N).', 'Min-heap of list heads.', 'Divide and conquer merge pairs.'],
    editorial: editorial('Flatten and sort.', 'Heap k-way merge.', 'Pairwise merge lists — O(N log k).', 'O(N log k)', 'O(k)'),
    relatedSlugs: ['merge-sorted-array', 'merge-intervals', 'find-median-from-data-stream'],
    orderIndex: 47,
    py: `import heapq\nlists = data["lists"]\nh = []\nfor i, arr in enumerate(lists):\n    if arr:\n        heapq.heappush(h, (arr[0], i, 0))\nres = []\nwhile h:\n    v, li, idx = heapq.heappop(h)\n    res.append(v)\n    if idx + 1 < len(lists[li]):\n        heapq.heappush(h, (lists[li][idx + 1], li, idx + 1))\nresult = res`,
    js: `const lists = data.lists;\nconst heap = [];\nfor (let i = 0; i < lists.length; i++) if (lists[i].length) heap.push({ v: lists[i][0], i, idx: 0 });\nheap.sort((a, b) => a.v - b.v);\nconst res = [];\nwhile (heap.length) {\n  const { v, i, idx } = heap.shift();\n  res.push(v);\n  if (idx + 1 < lists[i].length) {\n    heap.push({ v: lists[i][idx + 1], i, idx: idx + 1 });\n    heap.sort((a, b) => a.v - b.v);\n  }\n}\nconst result = res;`,
    testCases: [
      { input: '{"lists":[[1,4,5],[1,3,4],[2,6]]}', expectedOutput: '[1,1,2,3,4,4,5,6]' },
      { input: '{"lists":[]}', expectedOutput: '[]', isHidden: true },
    ],
  },
  {
    slug: 'trapping-rain-water',
    title: 'Trapping Rain Water',
    difficulty: 'HARD',
    topic: 'ARRAYS',
    tags: ['array', 'two-pointers', 'stack'],
    companies: BIG_TECH,
    description: 'Compute trapped water between elevation bars.',
    fullDescription: `Given non-negative integers \`height\` representing elevation map width 1, compute how much water can be trapped after rain.`,
    constraints: `n == height.length\n1 <= n <= 2 * 10^4`,
    examples: [
      { input: 'height = [0,1,0,2,1,0,1,3,2,1,2,1]', output: '6' },
      { input: 'height = [4,2,0,3,2,5]', output: '9' },
    ],
    edgeCases: ['Monotonic increasing traps 0', 'Valley in middle'],
    hints: ['Water at i = min(maxLeft, maxRight) - height[i].', 'Prefix max arrays.', 'Two pointers from both ends.'],
    editorial: editorial('Per index scan max left/right — O(n^2).', 'Prefix max arrays O(n).', 'Two-pointer O(1) space.', 'O(n)', 'O(1)'),
    relatedSlugs: ['container-with-most-water', 'product-of-array-except-self', 'maximum-subarray'],
    orderIndex: 48,
    py: `h = data["height"]\nl, r = 0, len(h) - 1\nlm = rm = 0\nw = 0\nwhile l < r:\n    if h[l] < h[r]:\n        lm = max(lm, h[l])\n        w += lm - h[l]\n        l += 1\n    else:\n        rm = max(rm, h[r])\n        w += rm - h[r]\n        r -= 1\nresult = w`,
    js: `const h = data.height;\nlet l = 0, r = h.length - 1, lm = 0, rm = 0, w = 0;\nwhile (l < r) {\n  if (h[l] < h[r]) { lm = Math.max(lm, h[l]); w += lm - h[l++]; }\n  else { rm = Math.max(rm, h[r]); w += rm - h[r--]; }\n}\nconst result = w;`,
    testCases: [
      { input: '{"height":[0,1,0,2,1,0,1,3,2,1,2,1]}', expectedOutput: '6' },
      { input: '{"height":[4,2,0,3,2,5]}', expectedOutput: '9', isHidden: true },
    ],
  },
  {
    slug: 'longest-palindromic-substring',
    title: 'Longest Palindromic Substring',
    difficulty: 'MEDIUM',
    topic: 'STRINGS',
    tags: ['string', 'dynamic-programming'],
    companies: BIG_TECH,
    description: 'Return the longest palindromic substring of s.',
    fullDescription: `Given a string \`s\`, return the **longest palindromic substring** in \`s\`.`,
    constraints: `1 <= s.length <= 1000`,
    examples: [
      { input: 's = "babad"', output: '"bab" or "aba"' },
      { input: 's = "cbbd"', output: '"bb"' },
    ],
    edgeCases: ['Entire string palindrome', 'Even length palindrome center between chars'],
    hints: ['Expand around each center (odd/even).', 'DP[i][j] if s[i]==s[j] and inner palindrome.', 'Manacher algorithm for linear time.'],
    editorial: editorial('Check all substrings — O(n^3).', 'Expand around center O(n^2).', 'Manacher O(n) — advanced.', 'O(n^2)', 'O(1)'),
    relatedSlugs: ['palindromic-substrings', 'valid-parentheses', 'longest-substring-without-repeating-characters'],
    orderIndex: 49,
    py: `s = data["s"]\nbest = ""\ndef expand(l, r):\n    while l >= 0 and r < len(s) and s[l] == s[r]:\n        l -= 1; r += 1\n    return s[l + 1:r]\nfor i in range(len(s)):\n    a = expand(i, i)\n    b = expand(i, i + 1)\n    cand = a if len(a) >= len(b) else b\n    if len(cand) > len(best):\n        best = cand\nresult = best`,
    js: `const s = data.s;\nlet best = "";\nfunction expand(l, r) {\n  while (l >= 0 && r < s.length && s[l] === s[r]) { l--; r++; }\n  return s.slice(l + 1, r);\n}\nfor (let i = 0; i < s.length; i++) {\n  const a = expand(i, i), b = expand(i, i + 1);\n  const cand = a.length >= b.length ? a : b;\n  if (cand.length > best.length) best = cand;\n}\nconst result = best;`,
    testCases: [
      { input: '{"s":"babad"}', expectedOutput: '"bab"' },
      { input: '{"s":"cbbd"}', expectedOutput: '"bb"', isHidden: true },
    ],
  },
];
