import type { ProblemDef } from '../types.js';
import { editorial } from '../helpers.js';

const BIG_TECH = ['Google', 'Amazon', 'Meta', 'Microsoft'];

export const BATCH_04: ProblemDef[] = [
  {
    slug: 'number-of-islands',
    title: 'Number of Islands',
    difficulty: 'MEDIUM',
    topic: 'GRAPHS',
    tags: ['graph', 'dfs', 'bfs', 'union-find'],
    companies: BIG_TECH,
    description: 'Count islands of 1s in a 2D grid.',
    fullDescription: `Given an \`m x n\` 2D binary grid \`grid\` which represents a map of \`'1'\`s (land) and \`'0'\`s (water), return the number of **islands**.`,
    constraints: `m == grid.length\nn == grid[i].length\n1 <= m, n <= 300`,
    examples: [
      { input: 'grid = [["1","1","0"],["0","1","0"],["1","0","1"]]', output: '3' },
      { input: 'grid = [["1","1","1"],["0","1","0"],["1","1","1"]]', output: '1' },
    ],
    edgeCases: ['All water returns 0', 'Single cell grid'],
    hints: ['Each unvisited 1 starts a new island.', 'DFS/BFS flood fill mark visited.', 'Union-find merges adjacent land.'],
    editorial: editorial('Mark all cells, count components.', 'DFS sink islands in-place.', 'BFS queue flood fill.', 'O(m*n)', 'O(m*n)'),
    relatedSlugs: ['max-area-of-island', 'surrounded-regions', 'clone-graph'],
    orderIndex: 30,
    py: `grid = data["grid"]\nrows, cols = len(grid), len(grid[0])\ncount = 0\ndef dfs(r,c):\n    if r<0 or c<0 or r>=rows or c>=cols or grid[r][c] != "1":\n        return\n    grid[r][c] = "0"\n    dfs(r+1,c); dfs(r-1,c); dfs(r,c+1); dfs(r,c-1)\nfor r in range(rows):\n    for c in range(cols):\n        if grid[r][c] == "1":\n            count += 1\n            dfs(r,c)\nresult = count`,
    js: `const grid = data.grid.map((row) => [...row]);\nlet count = 0;\nconst R = grid.length, C = grid[0].length;\nfunction dfs(r, c) {\n  if (r < 0 || c < 0 || r >= R || c >= C || grid[r][c] !== '1') return;\n  grid[r][c] = '0';\n  dfs(r + 1, c); dfs(r - 1, c); dfs(r, c + 1); dfs(r, c - 1);\n}\nfor (let r = 0; r < R; r++) for (let c = 0; c < C; c++) if (grid[r][c] === '1') { count++; dfs(r, c); }\nconst result = count;`,
    testCases: [
      { input: '{"grid":[["1","1","0"],["0","1","0"],["1","0","1"]]}', expectedOutput: '3' },
      { input: '{"grid":[["1","1","1"],["0","1","0"],["1","1","1"]]}', expectedOutput: '1', isHidden: true },
    ],
  },
  {
    slug: 'course-schedule',
    title: 'Course Schedule',
    difficulty: 'MEDIUM',
    topic: 'GRAPHS',
    tags: ['graph', 'topological-sort', 'dfs'],
    companies: BIG_TECH,
    description: 'Return true if all courses can be finished (no cycle).',
    fullDescription: `There are \`numCourses\` courses labeled \`0..numCourses-1\`. \`prerequisites[i] = [a,b]\` means take \`b\` before \`a\`. Return \`true\` if you can finish all courses.`,
    constraints: `1 <= numCourses <= 2000\n0 <= prerequisites.length <= 5000`,
    examples: [
      { input: 'numCourses = 2, prerequisites = [[1,0]]', output: 'true' },
      { input: 'numCourses = 2, prerequisites = [[1,0],[0,1]]', output: 'false' },
    ],
    edgeCases: ['No prerequisites always true', 'Self-loop via two edges'],
    hints: ['Model directed graph of prerequisites.', 'Cycle detection in directed graph.', 'Kahn topological sort BFS in-degree.'],
    editorial: editorial('Try all orderings — factorial.', 'DFS cycle detection with 3 colors.', 'Kahn BFS topological order.', 'O(V+E)', 'O(V+E)'),
    relatedSlugs: ['course-schedule-ii', 'alien-dictionary', 'graph-valid-tree'],
    orderIndex: 31,
    py: `n = data["numCourses"]\ngraph = [[] for _ in range(n)]\nfor a,b in data["prerequisites"]:\n    graph[b].append(a)\nstate = [0]*n\ndef dfs(u):\n    if state[u] == 1: return False\n    if state[u] == 2: return True\n    state[u] = 1\n    for v in graph[u]:\n        if not dfs(v): return False\n    state[u] = 2\n    return True\nresult = all(dfs(i) for i in range(n))`,
    js: `const n = data.numCourses;\nconst g = Array.from({ length: n }, () => []);\nfor (const [a, b] of data.prerequisites) g[b].push(a);\nconst st = Array(n).fill(0);\nfunction dfs(u) {\n  if (st[u] === 1) return false;\n  if (st[u] === 2) return true;\n  st[u] = 1;\n  for (const v of g[u]) if (!dfs(v)) return false;\n  st[u] = 2;\n  return true;\n}\nconst result = [...Array(n).keys()].every(dfs);`,
    testCases: [
      { input: '{"numCourses":2,"prerequisites":[[1,0]]}', expectedOutput: 'true' },
      { input: '{"numCourses":2,"prerequisites":[[1,0],[0,1]]}', expectedOutput: 'false', isHidden: true },
    ],
  },
  {
    slug: 'clone-graph',
    title: 'Clone Graph',
    difficulty: 'MEDIUM',
    topic: 'GRAPHS',
    tags: ['graph', 'dfs', 'bfs', 'hash-table'],
    companies: ['Meta', 'Amazon', 'Google'],
    description: 'Deep clone adjacency list graph given as node id map.',
    fullDescription: `Given an adjacency list \`graph\` where keys are node ids and values are neighbor id lists, return a **deep copy** of the graph as the same map structure with new implicit nodes.`,
    constraints: `Number of nodes <= 100`,
    examples: [
      { input: 'graph = {"1":[2],"2":[1]}', output: '{"1":[2],"2":[1]} (structure)' },
      { input: 'graph = {}', output: '{}' },
    ],
    edgeCases: ['Empty graph', 'Disconnected components'],
    hints: ['Map old id -> new id.', 'DFS/BFS copy neighbors recursively.', 'Avoid infinite loops with visited map.'],
    editorial: editorial('Serialize and deserialize.', 'DFS with hash map clone.', 'BFS queue cloning.', 'O(V+E)', 'O(V)'),
    relatedSlugs: ['copy-list-with-random-pointer', 'number-of-islands', 'course-schedule'],
    orderIndex: 32,
    py: `import copy\nresult = copy.deepcopy(data["graph"])`,
    js: `const result = JSON.parse(JSON.stringify(data.graph));`,
    testCases: [
      { input: '{"graph":{"1":[2],"2":[1]}}', expectedOutput: '{"1":[2],"2":[1]}' },
      { input: '{"graph":{}}', expectedOutput: '{}', isHidden: true },
    ],
  },
  {
    slug: 'rotting-oranges',
    title: 'Rotting Oranges',
    difficulty: 'MEDIUM',
    topic: 'GRAPHS',
    tags: ['graph', 'bfs', 'matrix'],
    companies: ['Amazon', 'Microsoft'],
    description: 'Minimum minutes until no fresh orange remains.',
    fullDescription: `You are given an \`m x n\` grid. Each cell: \`0\` empty, \`1\` fresh, \`2\` rotten. Every minute rotten oranges rot 4-directional neighbors. Return minimum minutes until no fresh, or \`-1\`.`,
    constraints: `1 <= m, n <= 10`,
    examples: [
      { input: 'grid = [[2,1,1],[1,1,0],[0,1,1]]', output: '4' },
      { input: 'grid = [[2,1,1],[0,1,1],[1,0,1]]', output: '-1' },
    ],
    edgeCases: ['No fresh oranges -> 0', 'Unreachable fresh -> -1'],
    hints: ['Multi-source BFS from all rotten.', 'Track minutes per wave.', 'Count fresh to verify all rotted.'],
    editorial: editorial('Simulate minute by minute naively.', 'BFS with time layers.', 'Deque all rotten then expand.', 'O(m*n)', 'O(m*n)'),
    relatedSlugs: ['number-of-islands', 'word-ladder', '01-matrix'],
    orderIndex: 33,
    py: `from collections import deque\ngrid = [row[:] for row in data["grid"]]\nR,C=len(grid),len(grid[0])\nq=deque()\nfresh=0\nfor r in range(R):\n    for c in range(C):\n        if grid[r][c]==1: fresh+=1\n        elif grid[r][c]==2: q.append((r,c,0))\nsteps=0\nwhile q:\n    r,c,t=q.popleft(); steps=max(steps,t)\n    for dr,dc in ((1,0),(-1,0),(0,1),(0,-1)):\n        nr,nc=r+dr,c+dc\n        if 0<=nr<R and 0<=nc<C and grid[nr][nc]==1:\n            grid[nr][nc]=2; fresh-=1; q.append((nr,nc,t+1))\nresult = -1 if fresh else steps`,
    js: `const grid = data.grid.map((r) => [...r]);\nconst R = grid.length, C = grid[0].length;\nconst q = [];\nlet fresh = 0, steps = 0;\nfor (let r = 0; r < R; r++) for (let c = 0; c < C; c++) {\n  if (grid[r][c] === 1) fresh++;\n  else if (grid[r][c] === 2) q.push([r, c, 0]);\n}\nwhile (q.length) {\n  const [r, c, t] = q.shift();\n  steps = Math.max(steps, t);\n  for (const [dr, dc] of [[1,0],[-1,0],[0,1],[0,-1]]) {\n    const nr = r + dr, nc = c + dc;\n    if (nr >= 0 && nc >= 0 && nr < R && nc < C && grid[nr][nc] === 1) {\n      grid[nr][nc] = 2; fresh--; q.push([nr, nc, t + 1]);\n    }\n  }\n}\nconst result = fresh ? -1 : steps;`,
    testCases: [
      { input: '{"grid":[[2,1,1],[1,1,0],[0,1,1]]}', expectedOutput: '4' },
      { input: '{"grid":[[2,1,1],[0,1,1],[1,0,1]]}', expectedOutput: '-1', isHidden: true },
    ],
  },
  {
    slug: 'coin-change',
    title: 'Coin Change',
    difficulty: 'MEDIUM',
    topic: 'DP',
    tags: ['dynamic-programming', 'bfs'],
    companies: BIG_TECH,
    description: 'Fewest coins needed to make amount, or -1.',
    fullDescription: `Given integer array \`coins\` and amount \`amount\`, return the **fewest** coins needed to make up that amount, or \`-1\` if impossible.`,
    constraints: `1 <= coins.length <= 12\n0 <= amount <= 10^4`,
    examples: [
      { input: 'coins = [1,2,5], amount = 11', output: '3', explanation: '5+5+1' },
      { input: 'coins = [2], amount = 3', output: '-1' },
    ],
    edgeCases: ['amount 0 returns 0', 'Greedy fails for some coin systems'],
    hints: ['Try all combinations — exponential.', 'dp[a] = min coins for amount a.', 'For each coin relax dp[a+coin].'],
    editorial: editorial('BFS on amounts.', 'Top-down memo recursion.', 'Bottom-up DP array.', 'O(amount * coins)', 'O(amount)'),
    relatedSlugs: ['coin-change-ii', 'combination-sum', 'house-robber'],
    orderIndex: 34,
    py: `amount = data["amount"]\ncoins = data["coins"]\ndp = [10**9] * (amount + 1)\ndp[0] = 0\nfor a in range(1, amount + 1):\n    for c in coins:\n        if c <= a:\n            dp[a] = min(dp[a], dp[a - c] + 1)\nresult = -1 if dp[amount] > amount else dp[amount]`,
    js: `const { amount, coins } = data;\nconst dp = Array(amount + 1).fill(Infinity);\ndp[0] = 0;\nfor (let a = 1; a <= amount; a++) for (const c of coins) if (c <= a) dp[a] = Math.min(dp[a], dp[a - c] + 1);\nconst result = dp[amount] === Infinity ? -1 : dp[amount];`,
    testCases: [
      { input: '{"coins":[1,2,5],"amount":11}', expectedOutput: '3' },
      { input: '{"coins":[2],"amount":3}', expectedOutput: '-1', isHidden: true },
    ],
  },
  {
    slug: 'house-robber',
    title: 'House Robber',
    difficulty: 'MEDIUM',
    topic: 'DP',
    tags: ['dynamic-programming', 'array'],
    companies: BIG_TECH,
    description: 'Max money robbing non-adjacent houses.',
    fullDescription: `Given integer array \`nums\` representing money in each house, return the **maximum** you can rob **without robbing two adjacent houses**.`,
    constraints: `1 <= nums.length <= 100\n0 <= nums[i] <= 400`,
    examples: [
      { input: 'nums = [1,2,3,1]', output: '4', explanation: 'Rob house 1 and 3: 1+3=4.' },
      { input: 'nums = [2,7,9,3,1]', output: '12' },
    ],
    edgeCases: ['One house', 'Take max of two if two houses'],
    hints: ['Include house i or skip it.', 'dp[i] = max(dp[i-1], dp[i-2]+nums[i]).', 'Compress to two variables prev/curr.'],
    editorial: editorial('Try all subsets without adjacent — 2^n.', 'DP array tabulation.', 'O(1) space rolling max.', 'O(n)', 'O(1)'),
    relatedSlugs: ['house-robber-ii', 'climbing-stairs', 'coin-change'],
    orderIndex: 35,
    py: `prev = curr = 0\nfor n in data["nums"]:\n    prev, curr = curr, max(curr, prev + n)\nresult = curr`,
    js: `let prev = 0, curr = 0;\nfor (const n of data.nums) [prev, curr] = [curr, Math.max(curr, prev + n)];\nconst result = curr;`,
    testCases: [
      { input: '{"nums":[1,2,3,1]}', expectedOutput: '4' },
      { input: '{"nums":[2,7,9,3,1]}', expectedOutput: '12', isHidden: true },
    ],
  },
  {
    slug: 'word-break',
    title: 'Word Break',
    difficulty: 'MEDIUM',
    topic: 'DP',
    tags: ['dynamic-programming', 'string', 'trie'],
    companies: ['Amazon', 'Google', 'Facebook'],
    description: 'Return true if s can be segmented into dictionary words.',
    fullDescription: `Given string \`s\` and dictionary \`wordDict\`, return \`true\` if \`s\` can be segmented into space-separated dictionary words.`,
    constraints: `1 <= s.length <= 300\n1 <= wordDict.length <= 1000`,
    examples: [
      { input: 's = "leetcode", wordDict = ["leet","code"]', output: 'true' },
      { input: 's = "applepenapple", wordDict = ["apple","pen"]', output: 'true' },
    ],
    edgeCases: ['Reuse words allowed', 'No valid segmentation'],
    hints: ['Try all splits recursively with memo.', 'dp[i] = can segment s[:i].', 'For each j<i if dp[j] and s[j:i] in dict.'],
    editorial: editorial('Backtracking all cuts.', 'Memoized recursion on index.', 'Bottom-up boolean DP.', 'O(n^2 * L)', 'O(n)'),
    relatedSlugs: ['word-break-ii', 'word-ladder', 'longest-increasing-subsequence'],
    orderIndex: 36,
    py: `s, words = data["s"], set(data["wordDict"])\nn = len(s)\ndp = [False] * (n + 1)\ndp[0] = True\nfor i in range(1, n + 1):\n    for j in range(i):\n        if dp[j] and s[j:i] in words:\n            dp[i] = True\n            break\nresult = dp[n]`,
    js: `const s = data.s, words = new Set(data.wordDict);\nconst n = s.length;\nconst dp = Array(n + 1).fill(false);\ndp[0] = true;\nfor (let i = 1; i <= n; i++) for (let j = 0; j < i; j++) if (dp[j] && words.has(s.slice(j, i))) { dp[i] = true; break; }\nconst result = dp[n];`,
    testCases: [
      { input: '{"s":"leetcode","wordDict":["leet","code"]}', expectedOutput: 'true' },
      { input: '{"s":"catsandog","wordDict":["cats","dog","sand","and","cat"]}', expectedOutput: 'false', isHidden: true },
    ],
  },
  {
    slug: 'longest-increasing-subsequence',
    title: 'Longest Increasing Subsequence',
    difficulty: 'MEDIUM',
    topic: 'DP',
    tags: ['dynamic-programming', 'binary-search'],
    companies: BIG_TECH,
    description: 'Length of longest strictly increasing subsequence.',
    fullDescription: `Given integer array \`nums\`, return the length of the **longest strictly increasing subsequence**.`,
    constraints: `1 <= nums.length <= 2500\n-10^4 <= nums[i] <= 10^4`,
    examples: [
      { input: 'nums = [10,9,2,5,3,7,101,18]', output: '4', explanation: '[2,3,7,101].' },
      { input: 'nums = [0,1,0,3,2,3]', output: '4' },
    ],
    edgeCases: ['Descending array length 1', 'Duplicates require strictly increasing'],
    hints: ['dp[i] = LIS ending at i — O(n^2).', 'Maintain pile tops array.', 'Binary search position for nums[i].'],
    editorial: editorial('O(n^2) DP per ending index.', 'Patience sorting piles.', 'tails binary search — O(n log n).', 'O(n log n)', 'O(n)'),
    relatedSlugs: ['number-of-longest-increasing-subsequence', 'russian-doll-envelopes', 'maximum-subarray'],
    orderIndex: 37,
    py: `import bisect\nnums = data["nums"]\ntails = []\nfor x in nums:\n    i = bisect.bisect_left(tails, x)\n    if i == len(tails):\n        tails.append(x)\n    else:\n        tails[i] = x\nresult = len(tails)`,
    js: `const nums = data.nums;\nconst tails = [];\nfor (const x of nums) {\n  let lo = 0, hi = tails.length;\n  while (lo < hi) { const mid = (lo + hi) >> 1; if (tails[mid] < x) lo = mid + 1; else hi = mid; }\n  tails[lo] = x;\n}\nconst result = tails.length;`,
    testCases: [
      { input: '{"nums":[10,9,2,5,3,7,101,18]}', expectedOutput: '4' },
      { input: '{"nums":[0,1,0,3,2,3]}', expectedOutput: '4', isHidden: true },
    ],
  },
  {
    slug: 'unique-paths',
    title: 'Unique Paths',
    difficulty: 'MEDIUM',
    topic: 'DP',
    tags: ['dynamic-programming', 'math'],
    companies: BIG_TECH,
    description: 'Count paths from top-left to bottom-right in grid.',
    fullDescription: `There is a robot on an \`m x n\` grid starting top-left. It can only move **right** or **down**. Return the number of unique paths to bottom-right.`,
    constraints: `1 <= m, n <= 100`,
    examples: [
      { input: 'm = 3, n = 7', output: '28' },
      { input: 'm = 3, n = 2', output: '3' },
    ],
    edgeCases: ['1x1 grid has 1 path', 'Single row or column'],
    hints: ['Paths to cell = paths from top + left.', 'dp[r][c] tabulation.', 'Combinatorics: C(m+n-2, m-1).'],
    editorial: editorial('DFS all paths — exponential.', '2D DP table.', '1D DP rolling row or math combinatorics.', 'O(m*n)', 'O(n)'),
    relatedSlugs: ['unique-paths-ii', 'minimum-path-sum', 'climbing-stairs'],
    orderIndex: 38,
    py: `m, n = data["m"], data["n"]\nrow = [1] * n\nfor _ in range(1, m):\n    for j in range(1, n):\n        row[j] += row[j - 1]\nresult = row[-1]`,
    js: `const { m, n } = data;\nconst row = Array(n).fill(1);\nfor (let r = 1; r < m; r++) for (let c = 1; c < n; c++) row[c] += row[c - 1];\nconst result = row[n - 1];`,
    testCases: [
      { input: '{"m":3,"n":7}', expectedOutput: '28' },
      { input: '{"m":3,"n":2}', expectedOutput: '3', isHidden: true },
    ],
  },
  {
    slug: 'jump-game',
    title: 'Jump Game',
    difficulty: 'MEDIUM',
    topic: 'GREEDY',
    tags: ['greedy', 'array', 'dynamic-programming'],
    companies: ['Amazon', 'Microsoft', 'Apple'],
    description: 'Return true if you can reach the last index.',
    fullDescription: `Given non-negative integer array \`nums\` where each element is max jump length from that index, return \`true\` if you can reach the **last index**, starting at index 0.`,
    constraints: `1 <= nums.length <= 10^4\n0 <= nums[i] <= 10^5`,
    examples: [
      { input: 'nums = [2,3,1,1,4]', output: 'true' },
      { input: 'nums = [3,2,1,0,4]', output: 'false' },
    ],
    edgeCases: ['Single element always true', 'Zero at non-last can block'],
    hints: ['Track farthest reachable index.', 'If i > farthest, stuck.', 'Update farthest = max(farthest, i+nums[i]).'],
    editorial: editorial('DP canReach[i].', 'Backtracking from end.', 'Greedy farthest reach.', 'O(n)', 'O(1)'),
    relatedSlugs: ['jump-game-ii', 'gas-station', 'maximum-subarray'],
    orderIndex: 39,
    py: `far = 0\nfor i, jump in enumerate(data["nums"]):\n    if i > far:\n        result = False\n        break\n    far = max(far, i + jump)\nelse:\n    result = True`,
    js: `let far = 0, result = true;\nfor (let i = 0; i < data.nums.length; i++) {\n  if (i > far) { result = false; break; }\n  far = Math.max(far, i + data.nums[i]);\n}`,
    testCases: [
      { input: '{"nums":[2,3,1,1,4]}', expectedOutput: 'true' },
      { input: '{"nums":[3,2,1,0,4]}', expectedOutput: 'false', isHidden: true },
    ],
  },
];
